# Generated by Django 4.0.1 on 2022-02-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('keywords', models.TextField()),
                ('archive', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
