# Generated by Django 4.0.1 on 2022-03-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_searchrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='keywords',
        ),
    ]
